import { Injectable } from '@angular/core';
import { Home } from "./Home";
import { Homes } from "./mock-homes";
import { User } from "./User";
import { Person } from "./Person";
import { Review } from "./Review";

@Injectable()
export class StorageService {
    Homes: Home[];
    CurrentUser: User = null;
    CurrentHome: Home = null;
    Criteria: string[] = ["rating", ""];

    getHomes(): Promise<Home[]> {
        return Promise.resolve(Homes);
    }
    getCurrentHome(): Home {
        return this.CurrentHome;
    }
    setCurrentHome(Home: Home): void {
        this.CurrentHome = Home;
    }
    getUser(): User {
        return this.CurrentUser;
    }
    LogIn(): void {
        this.CurrentUser = new User("Joe","Bloggs", "JoeBlogg@email.com", "test","0831234567",
            [
                new Person("Jane Doe", 90, "1234567n"),
                new Person("John Doe", 87, "1234567a")
            ],
            [
                new Home("JoeBloggs","ABC Homes", "Hollymount", "Sligo", "Ireland", 9.2, "0711234567", "ABC@email.ie", "Joe", "https://www.google.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],1, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 57,1, ""), new Review("Test", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 75,1, "")]),
                new Home("JoeBloggs","CDE Homes", "Glencarrig", "Sligo", "Ireland", 8.5, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[],[true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false], 2, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 21,1, "")]),
                new Home("JoeBloggs","BCD Homes", "Athenry", "Galway", "Ireland", 9.1, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],2, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 100,1, "")]),
                new Home("JoeBloggs","DEF Homes", "Listowel", "Kerry", "Ireland", 8.7, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],1, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 21,1, "")]),
                new Home("JoeBloggs","EFG Homes", "Ballymun", "Dublin", "Ireland", 8.9, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],3, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 100,1, "")]),
                new Home("JoeBloggs","FGH Homes", "Athlone", "Westmeath", "Ireland", 8.2, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],2, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 21, 1,"")]),
                new Home("JoeBloggs","GHI Homes", "Galway", "Galway", "Ireland", 9, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[],[true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false], 1, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 100, 1,"")]),
                new Home("JoeBloggs","HIJ Homes", "Finglas", "Dublin", "Ireland", 8.1, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],3, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 21, 1,"")]),
                new Home("JoeBloggs","CDE Homes", "Cartron", "Sligo", "Ireland", 9.5, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],2, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 100, 1,"")]),
                new Home("JoeBloggs","IJK Homes", "Tralee", "Kerry", "Ireland", 8.5, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],1, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 21, 1,"")]),
                new Home("JoeBloggs","JKL Homes", "Athlone", "Westmeath", "Ireland", 9.2, "0711234567", "ABC@email.ie", "Joe", "www.ABCHomes.ie", "www.report.ie", "50","10", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",[], [true,true,true,true,true,false,false,false,false,true,true,true,true,true,false,false,false,false],3, [new Review("HIQA", 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 9, "Mostly Compliant", 100, 1,"")])
            ]);
    }
    Logout(): void {
        this.CurrentUser = null;
    }
    setCriteria(criteria: string[]): void {
        this.Criteria = criteria;
    }
    getCriteria(): string[] {
        return this.Criteria;
    }
    UpdateReviews(Review: Review): void {
        this.CurrentHome.reviews.push(Review);
    }
}